/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanmodul1;

import javax.swing.JOptionPane;
/**
 *
 * @author dias
 */
public class FrameDua extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameL1S3
     */
    public FrameDua() {
        initComponents();
        FNama2.setText(FrameUtama.Nama);
        FTempatLahir2.setText(FrameUtama.TempatLahir);
        FTglLahir2.setText(FrameUtama.TglLahir);
        FJenisKelamin2.setText(FrameUtama.JenisKelamin);
        FAlamat2.setText(FrameUtama.Alamat);
        FTelp2.setText(FrameUtama.Telp);
        FEmail2.setText(FrameUtama.Email);
        FProdi2.setText(FrameUtama.Prodi);
        FFakultas2.setText(FrameUtama.Fakultas);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LJudul = new javax.swing.JLabel();
        LUniv = new javax.swing.JLabel();
        LAlamatUniv = new javax.swing.JLabel();
        LTelpUniv = new javax.swing.JLabel();
        LNama = new javax.swing.JLabel();
        LTempatLahir = new javax.swing.JLabel();
        LTglLahir = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        LAlamat = new javax.swing.JLabel();
        LTelp = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        LProdi = new javax.swing.JLabel();
        LFakultas = new javax.swing.JLabel();
        FNama2 = new javax.swing.JTextField();
        FTempatLahir2 = new javax.swing.JTextField();
        FTglLahir2 = new javax.swing.JTextField();
        FAlamat2 = new javax.swing.JTextField();
        FTelp2 = new javax.swing.JTextField();
        FEmail2 = new javax.swing.JTextField();
        FProdi2 = new javax.swing.JTextField();
        FJenisKelamin2 = new javax.swing.JTextField();
        FFakultas2 = new javax.swing.JTextField();
        BKeluar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        LJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LJudul.setText("UKM FORM REGISTRATION");

        LUniv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LUniv.setText("UNIVERSITAS TRUNOJOYO MADURA");

        LAlamatUniv.setText("JL. Raya Telang, PO. Box. 2 Kamal, Bangkalan- Madura");

        LTelpUniv.setText("Telp : (031) 3011146, Fax. (031) 3011506");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LUniv)
                            .addComponent(LJudul))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(LAlamatUniv)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(LTelpUniv)
                        .addGap(129, 129, 129))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LUniv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAlamatUniv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTelpUniv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LNama.setForeground(new java.awt.Color(255, 255, 255));
        LNama.setText("Nama : ");

        LTempatLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTempatLahir.setForeground(new java.awt.Color(255, 255, 255));
        LTempatLahir.setText("Tempat Lahir : ");

        LTglLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTglLahir.setForeground(new java.awt.Color(255, 255, 255));
        LTglLahir.setText("Tanggal Lahir : ");

        LJenisKelamin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LJenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
        LJenisKelamin.setText("Jenis Kelamin : ");

        LAlamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LAlamat.setForeground(new java.awt.Color(255, 255, 255));
        LAlamat.setText("Alamat : ");

        LTelp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTelp.setForeground(new java.awt.Color(255, 255, 255));
        LTelp.setText("No. Telp. : ");

        LEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email : ");

        LProdi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LProdi.setForeground(new java.awt.Color(255, 255, 255));
        LProdi.setText("Prodi : ");

        LFakultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LFakultas.setForeground(new java.awt.Color(255, 255, 255));
        LFakultas.setText("Fakultas : ");

        FNama2.setEditable(false);

        FTempatLahir2.setEditable(false);

        FTglLahir2.setEditable(false);

        FAlamat2.setEditable(false);

        FTelp2.setEditable(false);

        FEmail2.setEditable(false);

        FProdi2.setEditable(false);

        FJenisKelamin2.setEditable(false);

        FFakultas2.setEditable(false);

        BKeluar2.setText("Keluar");
        BKeluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BKeluar2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LTempatLahir)
                                .addComponent(LNama)
                                .addComponent(LTglLahir))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FTglLahir2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(FNama2)
                                .addComponent(FTempatLahir2)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LJenisKelamin)
                                .addComponent(LAlamat)
                                .addComponent(LTelp)
                                .addComponent(LEmail)
                                .addComponent(LProdi)
                                .addComponent(LFakultas))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FAlamat2)
                                .addComponent(FTelp2)
                                .addComponent(FEmail2)
                                .addComponent(FProdi2)
                                .addComponent(FJenisKelamin2)
                                .addComponent(FFakultas2)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTempatLahir)
                    .addComponent(FTempatLahir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTglLahir)
                    .addComponent(FTglLahir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJenisKelamin)
                    .addComponent(FJenisKelamin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAlamat)
                    .addComponent(FAlamat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTelp)
                    .addComponent(FTelp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEmail)
                    .addComponent(FEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LProdi)
                    .addComponent(FProdi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LFakultas)
                    .addComponent(FFakultas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BKeluar2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKeluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluar2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BKeluar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKeluar2;
    private javax.swing.JTextField FAlamat2;
    private javax.swing.JTextField FEmail2;
    private javax.swing.JTextField FFakultas2;
    private javax.swing.JTextField FJenisKelamin2;
    private javax.swing.JTextField FNama2;
    private javax.swing.JTextField FProdi2;
    private javax.swing.JTextField FTelp2;
    private javax.swing.JTextField FTempatLahir2;
    private javax.swing.JTextField FTglLahir2;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel LAlamat;
    private javax.swing.JLabel LAlamatUniv;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LFakultas;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LNama;
    private javax.swing.JLabel LProdi;
    private javax.swing.JLabel LTelp;
    private javax.swing.JLabel LTelpUniv;
    private javax.swing.JLabel LTempatLahir;
    private javax.swing.JLabel LTglLahir;
    private javax.swing.JLabel LUniv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
