/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanmodul1;

import javax.swing.JOptionPane;
/**
 *
 * @author dias
 */
public class FrameUtama extends javax.swing.JFrame {
    public static String Nama, TempatLahir, TglLahir, Alamat, Telp, Email, Prodi, JenisKelamin, Fakultas;
    /**
     * Creates new form FrameL1S3
     */
    public FrameUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LJudul = new javax.swing.JLabel();
        LUniv = new javax.swing.JLabel();
        LAlamatUniv = new javax.swing.JLabel();
        LTelpUniv = new javax.swing.JLabel();
        LNama = new javax.swing.JLabel();
        LTempatLahir = new javax.swing.JLabel();
        LTglLahir = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        LAlamat = new javax.swing.JLabel();
        LTelp = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        LProdi = new javax.swing.JLabel();
        LFakultas = new javax.swing.JLabel();
        FNama = new javax.swing.JTextField();
        FTempatLahir = new javax.swing.JTextField();
        FTglLahir = new javax.swing.JTextField();
        RLaki = new javax.swing.JRadioButton();
        RPerempuan = new javax.swing.JRadioButton();
        FAlamat = new javax.swing.JTextField();
        FTelp = new javax.swing.JTextField();
        FEmail = new javax.swing.JTextField();
        FProdi = new javax.swing.JTextField();
        FFakultas = new javax.swing.JComboBox<>();
        CBKonfirmasi = new javax.swing.JCheckBox();
        BBatal = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        LJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LJudul.setText("UKM FORM REGISTRATION");

        LUniv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LUniv.setText("UNIVERSITAS TRUNOJOYO MADURA");

        LAlamatUniv.setText("JL. Raya Telang, PO. Box. 2 Kamal, Bangkalan- Madura");

        LTelpUniv.setText("Telp : (031) 3011146, Fax. (031) 3011506");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LUniv)
                            .addComponent(LJudul))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(LAlamatUniv)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(LTelpUniv)
                        .addGap(129, 129, 129))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LUniv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAlamatUniv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTelpUniv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LNama.setForeground(new java.awt.Color(255, 255, 255));
        LNama.setText("Nama : ");

        LTempatLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTempatLahir.setForeground(new java.awt.Color(255, 255, 255));
        LTempatLahir.setText("Tempat Lahir : ");

        LTglLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTglLahir.setForeground(new java.awt.Color(255, 255, 255));
        LTglLahir.setText("Tanggal Lahir : ");

        LJenisKelamin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LJenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
        LJenisKelamin.setText("Jenis Kelamin : ");

        LAlamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LAlamat.setForeground(new java.awt.Color(255, 255, 255));
        LAlamat.setText("Alamat : ");

        LTelp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTelp.setForeground(new java.awt.Color(255, 255, 255));
        LTelp.setText("No. Telp. : ");

        LEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email : ");

        LProdi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LProdi.setForeground(new java.awt.Color(255, 255, 255));
        LProdi.setText("Prodi : ");

        LFakultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LFakultas.setForeground(new java.awt.Color(255, 255, 255));
        LFakultas.setText("Fakultas : ");

        GenderGroup.add(RLaki);
        RLaki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RLaki.setForeground(new java.awt.Color(255, 255, 255));
        RLaki.setText("Laki-laki");

        GenderGroup.add(RPerempuan);
        RPerempuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        RPerempuan.setText("Perempuan");

        FFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Fakultas--", "Fakultas Teknik", "Fakultas Ilmu Pendidikan", "Fakultas Hukum", "Fakultas Ekonomi dan Bisnis", "Fakultas Pertanian", "Fakultas Ilmu Sosial dan Ilmu Budaya" }));

        CBKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        CBKonfirmasi.setText("Data Yang Saya Masukkan Sudah Benar");

        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(BReset)
                        .addGap(62, 62, 62)
                        .addComponent(BSimpan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTempatLahir)
                            .addComponent(LNama)
                            .addComponent(LTglLahir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(FNama)
                            .addComponent(FTempatLahir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LJenisKelamin)
                            .addComponent(LAlamat)
                            .addComponent(LTelp)
                            .addComponent(LEmail)
                            .addComponent(LProdi)
                            .addComponent(LFakultas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FAlamat)
                            .addComponent(FTelp)
                            .addComponent(FEmail)
                            .addComponent(FProdi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RLaki)
                                .addGap(32, 32, 32)
                                .addComponent(RPerempuan)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(FFakultas, 0, 249, Short.MAX_VALUE)))
                    .addComponent(CBKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTempatLahir)
                    .addComponent(FTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTglLahir)
                    .addComponent(FTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJenisKelamin)
                    .addComponent(RLaki)
                    .addComponent(RPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAlamat)
                    .addComponent(FAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTelp)
                    .addComponent(FTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEmail)
                    .addComponent(FEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LProdi)
                    .addComponent(FProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LFakultas)
                    .addComponent(FFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBKonfirmasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBatal)
                    .addComponent(BSimpan)
                    .addComponent(BReset))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if (!CBKonfirmasi.isSelected()||
            (!RLaki.isSelected())||
            FNama.getText().isEmpty()||
            FTempatLahir.getText().isEmpty()||
            FAlamat.getText().isEmpty()||
            FTelp.getText().isEmpty()||
            FEmail.getText().isEmpty()||
            FProdi.getText().isEmpty()||
            (FFakultas.getSelectedItem() == "--Fakultas--")){
            JOptionPane.showMessageDialog(this, "Data anda kurang lengkap/belum mengkonfirmasi", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }else{
            Nama = FNama.getText();
            TempatLahir = FTempatLahir.getText();
            TglLahir = FTglLahir.getText();
            Alamat = FAlamat.getText();
            Telp = FTelp.getText();
            Email = FEmail.getText();
            Prodi = FProdi.getText();
            
            JenisKelamin = "";
            if (RLaki.isSelected()){
                JenisKelamin = "Laki-laki";
            }else if (RPerempuan.isSelected()){
                JenisKelamin = "Perempuan";
            }
            
            Fakultas = (String) FFakultas.getSelectedItem();
            
            FrameDua output = new FrameDua();
            output.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_BSimpanActionPerformed

    //Aksi Reset
    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        FNama.setText( "");
        FTempatLahir.setText("");
        FTglLahir.setText("");
        FAlamat.setText("");
        FTelp.setText("");
        FEmail.setText("");
        FProdi.setText("");
        
        GenderGroup.clearSelection();
        
        FFakultas.setSelectedIndex(0);
        
        CBKonfirmasi.setSelected(false);
    }//GEN-LAST:event_BResetActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSimpan;
    private javax.swing.JCheckBox CBKonfirmasi;
    private javax.swing.JTextField FAlamat;
    private javax.swing.JTextField FEmail;
    private javax.swing.JComboBox<String> FFakultas;
    private javax.swing.JTextField FNama;
    private javax.swing.JTextField FProdi;
    private javax.swing.JTextField FTelp;
    private javax.swing.JTextField FTempatLahir;
    private javax.swing.JTextField FTglLahir;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel LAlamat;
    private javax.swing.JLabel LAlamatUniv;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LFakultas;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LNama;
    private javax.swing.JLabel LProdi;
    private javax.swing.JLabel LTelp;
    private javax.swing.JLabel LTelpUniv;
    private javax.swing.JLabel LTempatLahir;
    private javax.swing.JLabel LTglLahir;
    private javax.swing.JLabel LUniv;
    private javax.swing.JRadioButton RLaki;
    private javax.swing.JRadioButton RPerempuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
